# Generated by Django 5.2 on 2025-05-05 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('price_ars', models.FloatField()),
                ('image_url', models.URLField(max_length=100)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
