# Generated by Django 5.2 on 2025-05-09 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('danimax', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-scraped_at'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
